Repository SeattleColleges/belindas-closet-android, pull requests merged in 2023-11, with the labels that each got.

#106 belindas-closet-android_2_105_change-colors-to-NSC-colors
  app/src/main/java/com/example/belindas_closet/ui/theme/Color.kt
  app/src/main/java/com/example/belindas_closet/ui/theme/Theme.kt
Labels: enhancement, Sprint 2

#113 belinda_android-add_login_functionality-01
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/belindas_closet/data/network/HttpRoutes.kt
  app/src/main/java/com/example/belindas_closet/data/network/auth/LoginService.kt
  app/src/main/java/com/example/belindas_closet/data/network/auth/LoginServiceImpl.kt
  app/src/main/java/com/example/belindas_closet/data/network/dto/auth_dto/LoginRequest.kt
  app/src/main/java/com/example/belindas_closet/data/network/dto/auth_dto/LoginResponse.kt
  app/src/main/java/com/example/belindas_closet/screen/Login.kt
Labels: enhancement

#101 Belindas_android-100-add_product_page-01
  app/src/main/java/com/example/belindas_closet/screen/AddProduct.kt
  app/src/main/java/com/example/belindas_closet/screen/Home.kt
Labels: bug

#119 belinda_android-enhancement-118-forgot_password_function
  app/src/main/java/com/example/belindas_closet/data/network/HttpRoutes.kt
  app/src/main/java/com/example/belindas_closet/data/network/auth/ForgotPasswordService.kt
  app/src/main/java/com/example/belindas_closet/data/network/auth/ForgotPasswordServiceImpl.kt
  app/src/main/java/com/example/belindas_closet/data/network/dto/auth_dto/ForgotPasswordRequest.kt
  app/src/main/java/com/example/belindas_closet/data/network/dto/auth_dto/ForgotPasswordResponse.kt
  app/src/main/java/com/example/belindas_closet/screen/ForgotPassword.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#130 Belinda_Androis_Sprint_2_Added_Delete_Button
  app/src/main/java/com/example/belindas_closet/screen/Update.kt
Labels: Sprint 2

#129 belindas-closet-android_3_120_create-categories-for-other-clothing-types
  app/src/main/java/com/example/belindas_closet/data/Datasource.kt
  app/src/main/res/drawable/product10.png
  app/src/main/res/drawable/product11.png
  app/src/main/res/drawable/product12.png
  app/src/main/res/drawable/product13.png
  app/src/main/res/drawable/product14.png
  app/src/main/res/drawable/product15.png
  app/src/main/res/drawable/product16.png
  app/src/main/res/drawable/product17.png
  app/src/main/res/drawable/product18.png
  app/src/main/res/drawable/product5.png
  app/src/main/res/drawable/product6.png
  app/src/main/res/drawable/product7.png
  app/src/main/res/drawable/product8.png
  app/src/main/res/drawable/product9.png
Labels: enhancement, Sprint 3

#132 Belinda_Androis_Sprint_2_Fix_Duplicate_Text
  app/src/main/java/com/example/belindas_closet/screen/Update.kt
Labels: bug

#140 belinda-android_enhancement_139_signup-function
  app/src/main/java/com/example/belindas_closet/data/network/HttpRoutes.kt
  app/src/main/java/com/example/belindas_closet/data/network/auth/SignUpService.kt
  app/src/main/java/com/example/belindas_closet/data/network/auth/SignUpServiceImpl.kt
  app/src/main/java/com/example/belindas_closet/data/network/dto/auth_dto/SignUpRequest.kt
  app/src/main/java/com/example/belindas_closet/data/network/dto/auth_dto/SignUpResponse.kt
  app/src/main/java/com/example/belindas_closet/screen/Login.kt
  app/src/main/java/com/example/belindas_closet/screen/SignUp.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#134 belinda-android_02_133_display-new-product
  app/src/main/java/com/example/belindas_closet/screen/AddProduct.kt
Labels: Sprint 2

#146 belindas-closet-android_3_145_create-archive-product-button
  app/src/main/archive_icon-playstore.png
  app/src/main/java/com/example/belindas_closet/screen/IndividualProductUpdate.kt
  app/src/main/res/drawable/archive_icon.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, Sprint 3

#156 Enhancement 141 admin view 01
  app/src/main/java/com/example/belindas_closet/Routes.kt
  app/src/main/java/com/example/belindas_closet/screen/AdminView.kt
  app/src/main/java/com/example/belindas_closet/screen/Login.kt
  app/src/main/java/com/example/belindas_closet/screen/ScreenMain.kt
Labels: Sprint 3

#179 belinda-closet-android-04-177-change-product-model
  app/src/main/java/com/example/belindas_closet/data/Datasource.kt
  app/src/main/java/com/example/belindas_closet/model/Product.kt
  app/src/main/java/com/example/belindas_closet/screen/AddProduct.kt
Labels: Sprint 4

#190 Belinda_Android_Sprint_2_189_Navbar_SignUp_Page
  app/src/main/java/com/example/belindas_closet/screen/ForgotPassword.kt
  app/src/main/java/com/example/belindas_closet/screen/SignUp.kt
Labels: Sprint 2

#186 Belinda_Android_Sprint_2_184_Navbar_Login_Page
  app/src/main/java/com/example/belindas_closet/screen/Login.kt
Labels: Sprint 2

#195 belindas-closet-android_3_175_add-functionality-delete-button
  app/src/main/java/com/example/belindas_closet/data/network/HttpRoutes.kt
  app/src/main/java/com/example/belindas_closet/data/network/auth/DeleteService.kt
  app/src/main/java/com/example/belindas_closet/data/network/auth/DeleteServiceImpl.kt
  app/src/main/java/com/example/belindas_closet/data/network/dto/auth_dto/DeleteRequest.kt
  app/src/main/java/com/example/belindas_closet/data/network/dto/auth_dto/DeleteResponse.kt
  app/src/main/java/com/example/belindas_closet/screen/IndividualProductUpdate.kt
  app/src/main/java/com/example/belindas_closet/screen/Login.kt
  app/src/main/java/com/example/belindas_closet/screen/ProductDetail.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, Sprint 3

#196 belindas-closet-android_3_191-fix-products-for-same-category-disappearing
  app/src/main/java/com/example/belindas_closet/screen/IndividualProductUpdate.kt
  app/src/main/res/values/strings.xml
Labels: bug, Sprint 4

#202 belindas-android_03_194_navigation-update-pages_02
  app/src/main/java/com/example/belindas_closet/screen/IndividualProductUpdate.kt
  app/src/main/java/com/example/belindas_closet/screen/Update.kt
Labels: enhancement, Sprint 3, Fall

#203 belindas-closet-android-2-204-add-menu-to-add-product-page
  app/src/main/java/com/example/belindas_closet/screen/AddProduct.kt
Labels: Sprint 2

#206 belindas_closet_android_4_142_add_appropriate_mit_licensing-to-each_repository
  LICENSE.md
Labels: documentation, Sprint 4

#213 belinda-closet-android-product-menu-dropdown-01
  app/src/main/java/com/example/belindas_closet/screen/ProductDetail.kt
Labels: Sprint 4

#208 belinda-closet-android-04-207-add-button-image-picker
  app/build.gradle
  app/src/main/java/com/example/belindas_closet/screen/AddProduct.kt
  app/src/main/res/values/strings.xml
Labels: Sprint 4

#217 belindas-closet-android_4_216_finishing-tasks-for-belindas
  app/src/main/java/com/example/belindas_closet/screen/AddProduct.kt
  app/src/main/java/com/example/belindas_closet/screen/Login.kt
  app/src/main/res/drawable/nsc_mascot_green_cropped.png
  app/src/main/res/values/strings.xml
Labels: enhancement, Sprint 4
