Repository SeattleColleges/belindas-closet-android, pull requests merged in 2023-10, with the labels that each got.

#57 belindas-closet-android_1_46_create-a-registration-page
  app/src/main/java/com/example/belindas_closet/screen/SignUp.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, Sprint 1

#58 belindas-closet-android_1_55_fix-cancel-button
  app/src/main/java/com/example/belindas_closet/screen/Update.kt
Labels: bug, Sprint 1

#56 Belinda_Android_Sprint_1_44_deleting_AddProduct
  app/src/main/java/com/example/belindas_closet/screen/Login.kt
Labels: bug

#67 belindas-closet-android_1_60_registration_page_password_inputs
  app/src/main/java/com/example/belindas_closet/screen/SignUp.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, Sprint 1

#69 belindas-closet-android_1_68_fix-email-address-length
  app/src/main/java/com/example/belindas_closet/screen/Login.kt
Labels: bug, Sprint 1

#86 belindas-closet-android_2_80_toggles-for-password-inputs
  app/src/main/java/com/example/belindas_closet/screen/SignUp.kt
  app/src/main/res/drawable/baseline_visibility_24.xml
  app/src/main/res/drawable/baseline_visibility_off_24.xml
Labels: enhancement, Sprint 2

#85 belinda_android-02-84-refactor_product_model
  app/src/main/java/com/example/belindas_closet/data/Datasource.kt
  app/src/main/java/com/example/belindas_closet/model/Product.kt
  app/src/main/java/com/example/belindas_closet/screen/AddProduct.kt
  app/src/main/java/com/example/belindas_closet/screen/Home.kt
  app/src/main/java/com/example/belindas_closet/screen/IndividualProduct.kt
  app/src/main/java/com/example/belindas_closet/screen/IndividualProductUpdate.kt
  app/src/main/java/com/example/belindas_closet/screen/ProductDetail.kt
  app/src/main/java/com/example/belindas_closet/screen/Update.kt
Labels: Sprint 2

#95 belindas-closet-android_2_94_remove-name-and-add-nsc-logo
  app/src/main/java/com/example/belindas_closet/screen/Home.kt
  app/src/main/res/drawable/nsc_v_logo.png
  app/src/main/res/values/strings.xml
Labels: enhancement, Sprint 2

#91 belindas-closet-android-2-90-change-header-login-page
  app/src/main/java/com/example/belindas_closet/screen/Login.kt
  app/src/main/res/drawable/nsc_mascot_blue_cropped.png
  app/src/main/res/values/strings.xml
  build.gradle
Labels: enhancement, Sprint 2

#96 Belinda_Android_Sprint_1_73_Toast_Message_For _AddProduct Button2
  app/src/main/java/com/example/belindas_closet/screen/AddProduct.kt
Labels: Sprint 1
