Repository SeattleColleges/belindas-closet-android, pull requests merged in 2023-07, with the labels that each got.

#11 Refactor 3 update ci 02
  .github/workflows/ci.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  app/build.gradle
  app/src/test/java/unit_tests/ExampleUnitTest.kt
  build.gradle
Labels: Sprint 1

#8 Create login page
  app/build.gradle
  app/src/main/java/com/example/belindas_closet/MainActivity.kt
  app/src/main/java/com/example/belindas_closet/Routes.kt
  app/src/main/java/com/example/belindas_closet/screen/Login.kt
  app/src/main/java/com/example/belindas_closet/screen/ScreenMain.kt
  app/src/main/java/com/example/belindas_closet/screen/SignUp.kt
  app/src/main/java/com/example/belindas_closet/ui/theme/Color.kt
  app/src/main/java/com/example/belindas_closet/ui/theme/Theme.kt
  app/src/main/res/drawable/packaging.png
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Sprint 1

#9 Create dependabot.yml
  .github/dependabot.yml
Labels: Sprint 1

#15 Belindas-closet-android-2-14-update-sdk-from-33-to-34
  app/build.gradle
Labels: bug

#18 Belindas-closet-android-2-18-fix-compose-compiler-dependency-issue
  app/build.gradle
  build.gradle
Labels: dependencies

#23 belindas-closet-android_4_20_pr-template
  docs/pull_request_template.md
Labels: enhancement, Sprint 4

#22 belindas-closet-android_4_21_issue-templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement, Sprint 4

#25 Product functionality added
  app/src/main/java/com/example/belindas_closet/Routes.kt
  app/src/main/java/com/example/belindas_closet/data/Product.kt
  app/src/main/java/com/example/belindas_closet/screen/AddProduct.kt
  app/src/main/java/com/example/belindas_closet/screen/Login.kt
  app/src/main/java/com/example/belindas_closet/screen/ScreenMain.kt
Labels: enhancement, Sprint 4
