Repository SeattleColleges/belindas-closet-android, pull requests merged in 2023-08, with the labels that each got.

#28 Product functionality UI updated
  app/src/main/java/com/example/belindas_closet/Routes.kt
  app/src/main/java/com/example/belindas_closet/data/Product.kt
  app/src/main/java/com/example/belindas_closet/screen/AddProduct.kt
Labels: enhancement, Sprint 4

#30 belindas-closet-android_4_29_edit-issue-template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: bug, Sprint 4

#37 belinda_android_5_33-34_add update and delete UI
  app/src/main/java/com/example/belindas_closet/Routes.kt
  app/src/main/java/com/example/belindas_closet/data/Product.kt
  app/src/main/java/com/example/belindas_closet/screen/ProductDetail.kt
  app/src/main/java/com/example/belindas_closet/screen/ScreenMain.kt
  app/src/main/java/com/example/belindas_closet/screen/Update.kt
  app/src/main/res/values/strings.xml
Labels: Sprint 5
