Repository SeattleColleges/belindas-closet-android, pull requests merged in 2023-12, with the labels that each got.

#225 belindas_closet_android_4_142_delete_non_md_files
  .github/workflows/on-pull-request.yml
  LICENSE
  app/src/main/java/com/example/belindas_closet/screen/Login.kt
Labels: documentation, Sprint 4

#221 belindas-closet-android_3_210_logout-button-on-admin-page
  app/src/main/java/com/example/belindas_closet/screen/AdminView.kt
Labels: Sprint 3

#219 belinda-closet-android-04-218-reset-password-page-01
  app/src/main/java/com/example/belindas_closet/Routes.kt
  app/src/main/java/com/example/belindas_closet/screen/ResetPassword.kt
  app/src/main/java/com/example/belindas_closet/screen/ScreenMain.kt
  app/src/main/res/values/strings.xml
Labels: Sprint 4

#231 belindas-closet-android_4_176_modify-product-update-page
  app/src/main/java/com/example/belindas_closet/screen/Update.kt
Labels: enhancement, Sprint 4

#230 belindas-closet-android_4_229_add-donation-page
  app/src/main/java/com/example/belindas_closet/Routes.kt
  app/src/main/java/com/example/belindas_closet/screen/DonationInfo.kt
  app/src/main/java/com/example/belindas_closet/screen/Home.kt
  app/src/main/java/com/example/belindas_closet/screen/ScreenMain.kt
  app/src/main/res/drawable/info_icon.xml
  app/src/main/res/values/strings.xml
Labels: Sprint 4

#223 belinda-closet-android-220-revise-add-product-page-01
  app/src/main/java/com/example/belindas_closet/screen/AddProduct.kt
  app/src/main/res/values/strings.xml
Labels: Sprint 2

#234 belindas-android_4_167_edit-user-role
  app/build.gradle
  app/src/main/java/com/example/belindas_closet/Routes.kt
  app/src/main/java/com/example/belindas_closet/data/Datasource.kt
  app/src/main/java/com/example/belindas_closet/model/User.kt
  app/src/main/java/com/example/belindas_closet/screen/AdminView.kt
  app/src/main/java/com/example/belindas_closet/screen/EditUserRole.kt
  app/src/main/java/com/example/belindas_closet/screen/Home.kt
  app/src/main/java/com/example/belindas_closet/screen/ScreenMain.kt
Labels: enhancement, Sprint 4

#233 belindas-closet-android_3_108_creator-view-page
  app/src/main/java/com/example/belindas_closet/Routes.kt
  app/src/main/java/com/example/belindas_closet/screen/CreatorView.kt
  app/src/main/java/com/example/belindas_closet/screen/Login.kt
  app/src/main/java/com/example/belindas_closet/screen/ScreenMain.kt
Labels: enhancement, Sprint 3

#236 belindas-closet-android_4_235_edit-option-visiblity
  app/src/main/java/com/example/belindas_closet/data/network/dto/auth_dto/SignUpRequest.kt
  app/src/main/java/com/example/belindas_closet/screen/IndividualProduct.kt
  app/src/main/java/com/example/belindas_closet/screen/ProductDetail.kt
Labels: enhancement, Sprint 4
