Repository SeattleColleges/belindas-closet-android, pull requests merged in 2024-04, with the labels that each got.

#261 Belindas-closet-android-260-fix-android-templates
  .github/ISSUE_TEMPLATE/issue.md
  .github/ISSUE_TEMPLATE/user_story.md
  .github/pull_request_template.md
Labels: bug

#265 Belindas-closet-android-5-264-delete-issue-pull-request-templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue.md
  .github/ISSUE_TEMPLATE/user_story.md
  .github/pull_request_template.md
Labels: documentation, Sprint 5

#268 belinda-android-05-267-add-change-password-function
  app/src/main/java/com/example/belindas_closet/Routes.kt
  app/src/main/java/com/example/belindas_closet/data/network/HttpRoutes.kt
  app/src/main/java/com/example/belindas_closet/data/network/auth/ChangePasswordService.kt
  app/src/main/java/com/example/belindas_closet/data/network/auth/ChangePasswordServiceImpl.kt
  app/src/main/java/com/example/belindas_closet/data/network/dto/auth_dto/ChangPasswordRequest.kt
  app/src/main/java/com/example/belindas_closet/data/network/dto/auth_dto/ChangePasswordResponse.kt
  app/src/main/java/com/example/belindas_closet/screen/ChangePassword.kt
  app/src/main/java/com/example/belindas_closet/screen/ScreenMain.kt
  app/src/main/res/values/strings.xml
Labels: Sprint 5

#278 belindas-closet-android_5_271_add-profile-dropdown
  app/src/main/java/com/example/belindas_closet/Routes.kt
  app/src/main/java/com/example/belindas_closet/screen/AddProduct.kt
  app/src/main/java/com/example/belindas_closet/screen/AdminView.kt
  app/src/main/java/com/example/belindas_closet/screen/CreatorView.kt
  app/src/main/java/com/example/belindas_closet/screen/DonationInfo.kt
  app/src/main/java/com/example/belindas_closet/screen/EditUserRole.kt
  app/src/main/java/com/example/belindas_closet/screen/Home.kt
  app/src/main/java/com/example/belindas_closet/screen/IndividualProduct.kt
  app/src/main/java/com/example/belindas_closet/screen/IndividualProductUpdate.kt
  app/src/main/java/com/example/belindas_closet/screen/ProductDetail.kt
  app/src/main/java/com/example/belindas_closet/screen/Update.kt
Labels: Sprint 5
